DROP TABLE IF EXISTS `authorities`;
DROP TABLE IF EXISTS `users`;

-- CREATE EMPLOYEE TABLE
CREATE TABLE EMPLOYEE (
    ID IDENTITY PRIMARY KEY,
    EMPLOYEE_NAME VARCHAR(255) NOT NULL,
    EMPLOYEE_SALARY INT,
    DEPARTMENT VARCHAR(255)
);

-- CREATE USERS TABLE
CREATE TABLE `users` (
    USERNAME VARCHAR_IGNORECASE(50) NOT NULL PRIMARY KEY,
    PASSWORD VARCHAR_IGNORECASE(68) NOT NULL,
    ENABLED BOOLEAN NOT NULL
);

-- CREATE AUTHORITIES TABLE
CREATE TABLE `authorities` (
    USERNAME VARCHAR_IGNORECASE(50) NOT NULL,
    AUTHORITY VARCHAR_IGNORECASE(50) NOT NULL,
    CONSTRAINT FK_AUTHORITIES_USERS FOREIGN KEY(USERNAME) REFERENCES USERS(USERNAME)
);

CREATE UNIQUE INDEX IX_AUTH_USERNAME ON AUTHORITIES (USERNAME, AUTHORITY);